version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_web
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - certbot
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do sleep 1; done"
