name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd devops-adam || git clone https://github.com/zadam9/devops-adam.git
            cd devops-adam
            git pull origin main
            docker build -t mon-cv .
            docker rm -f cv-running || true
            docker run -d -p 80:80 --name cv-running mon-cv
